"""`memex ctx` — build a unified context block for Cursor hooks.

Combines:
  - mem profile (stable user info)
  - mem search (memories relevant to the current prompt)
  - doc search (wiki RAG hits relevant to the current prompt)

…wraps them in BEGIN/END markers, and respects a token budget.
"""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import typer
from rich.console import Console

from memex.backends.mem_store import PROFILE_CATEGORIES, MemStore
from memex.core.config import load_config
from memex.core.utils import count_tokens, truncate_to_tokens
from memex.core.wiki import Wiki

console = Console()

BEGIN = "<!-- BEGIN memex-context (auto-generated by memex ctx) -->"
END = "<!-- END memex-context -->"


def ctx(
    ctx_: typer.Context,
    query: str = typer.Argument("", help="The user's current prompt or topic."),
    write: Path = typer.Option(None, "--write", help="Write the block to this path."),
    budget: int = typer.Option(None, "--budget", help="Token budget (default from memex.yaml)."),
    top_k_docs: int = typer.Option(None, "-k", "--top-k-docs"),
    top_k_mems: int = typer.Option(None, "--top-k-mems"),
    no_profile: bool = typer.Option(False, "--no-profile"),
    no_memories: bool = typer.Option(False, "--no-memories"),
    no_docs: bool = typer.Option(False, "--no-docs"),
):
    """Build a unified context block (used by Cursor hooks)."""
    cfg = load_config(ctx_.obj.get("root") if ctx_.obj else None)
    budget_tokens = budget if budget is not None else cfg.ctx.budget_tokens

    include_profile = cfg.ctx.include_profile and not no_profile
    include_memories = cfg.ctx.include_memories and not no_memories
    include_docs = cfg.ctx.include_docs and not no_docs

    wiki = Wiki(cfg)
    mem = MemStore(cfg) if (include_profile or include_memories) else None

    k_docs = top_k_docs if top_k_docs is not None else cfg.search.top_k_docs
    k_mems = top_k_mems if top_k_mems is not None else cfg.search.top_k_mems

    def _profile_text() -> str:
        if not include_profile or mem is None:
            return ""
        items: list = []
        for cat in PROFILE_CATEGORIES:
            items.extend(mem.list(category=cat))
        if not items:
            return ""
        lines = ["## About the user", ""]
        for it in items[:20]:
            lines.append(f"- ({it.category}) {it.text}")
        return "\n".join(lines) + "\n"

    def _memory_text() -> str:
        if not include_memories or mem is None or not query.strip():
            return ""
        hits = mem.search(query, top_k=k_mems)
        # de-dup against profile content
        hits = [h for h in hits if h.category not in PROFILE_CATEGORIES]
        if not hits:
            return ""
        lines = ["## Relevant memories", ""]
        for h in hits:
            tag = f"({h.category})"
            lines.append(f"- {tag} {h.text}")
        return "\n".join(lines) + "\n"

    def _doc_text() -> str:
        if not include_docs or not query.strip():
            return ""
        try:
            hits = wiki.search(query, top_k=k_docs)
        except Exception as e:
            console.print(f"[yellow]warn:[/yellow] wiki search failed: {e}", style="dim")
            return ""
        if not hits:
            return ""
        lines = ["## Relevant docs", ""]
        for h in hits:
            heading = h.heading if h.heading and h.heading != "(root)" else ""
            heading_str = f" — {heading}" if heading else ""
            lines.append(f"### [{h.title}]({h.path}){heading_str}  (score {h.score:.2f})")
            for ln in h.text.strip().splitlines():
                lines.append(f"> {ln}")
            lines.append("")
        return "\n".join(lines)

    with ThreadPoolExecutor(max_workers=3) as pool:
        f_profile = pool.submit(_profile_text)
        f_mems = pool.submit(_memory_text)
        f_docs = pool.submit(_doc_text)
        profile_md = f_profile.result()
        memories_md = f_mems.result()
        docs_md = f_docs.result()

    body = _assemble(profile_md, memories_md, docs_md, budget=budget_tokens)
    block = f"{BEGIN}\n{body}\n{END}\n" if body.strip() else f"{BEGIN}\n_(no context)_\n{END}\n"

    if write:
        write.parent.mkdir(parents=True, exist_ok=True)
        write.write_text(block, encoding="utf-8")
        console.print(
            f"[green]✓[/green] wrote ctx ({count_tokens(block)} tokens) → {write}", style="dim"
        )
    else:
        typer.echo(block)


def _assemble(profile_md: str, memories_md: str, docs_md: str, *, budget: int) -> str:
    """Allocate the token budget across the three sections, biased to docs."""
    if budget <= 0:
        return ""

    parts = [p for p in (profile_md, memories_md, docs_md) if p.strip()]
    if not parts:
        return ""

    weights = []
    for p in (profile_md, memories_md, docs_md):
        if not p.strip():
            weights.append(0)
            continue
        weights.append(1 if p is profile_md else 2 if p is memories_md else 3)

    total_w = sum(weights) or 1
    quotas = [int(budget * w / total_w) for w in weights]

    profile_t = truncate_to_tokens(profile_md, quotas[0]) if profile_md else ""
    memories_t = truncate_to_tokens(memories_md, quotas[1]) if memories_md else ""
    docs_t = truncate_to_tokens(docs_md, quotas[2]) if docs_md else ""

    sections = [s for s in (profile_t, memories_t, docs_t) if s.strip()]
    return "\n".join(sections).strip()
